[colors.primary]
background = "#002020"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

[env]
TERM = "alacritty"

[font]
size = 7

[font.normal]
family = "JetBrainsMonoNLNerdFontMono"

[window]
opacity = 0.8
