[colors.primary]
background = "#002020"

[env]
TERM = "alacritty"

[font]
size = 13

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMonoNLNerdFontMono"
style = "Regular"

[window]
opacity = 0.8
